FROM ruby:2.5

RUN apt-get update && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  postgresql-client \
  yarn

WORKDIR /myapp

COPY Gemfile Gemfile.lock /myapp/

RUN bundle install

## 本番環境用の設定
COPY . .
CMD ["rails", "s"]